# Generated by Django 3.2 on 2021-04-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_slug', models.CharField(max_length=100)),
                ('heroku', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], max_length=100)),
                ('bootstrap', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], max_length=100)),
                ('custom_accounts', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], max_length=100)),
            ],
        ),
    ]
